### ISSUE TITLE
Add a protection to avoid to spam the snapcast server which make it crash !

### ISSUE THREAD

**Issue by atoomic** [atoomic/snapcast-volume-ui#6]
When sending in a short time multiple queries to the server...
it can happen that it reaches a state where he cannot recover...

This an upstream bug reported by @airdrummingfool there https://github.com/badaix/snapcast/issues/200
but we can be good citizen and try to add some internal protections to limit the queries.

On top of my mind:
- JS protection to add little timeout between two queries
- or file lock protection in the dancer app (better for multiple clients)

**Comment by airdrummingfool** [comment]
I agree that this is something to try to guard against, though I would like to see it solved in the snapcast repo ultimately.

My thoughts (very similar to yours):
* client or server side: prevent from sending more than one request at a time with some kind of queueing system. It would be even better if we could intelligently prune the queue, for example if queue has `[ hostA:50, hostB:20 ]` and then hostA is adjusted to 40, the original `hostA:50` would be dropped, to perform as few requests as possible.
* client-side: disable scroll wheel on the knob: http://stackoverflow.com/a/39366882/627772
* server-side: make the do_request method synchronized, so that all other requests wait until it to complete

**Comment by atoomic** [comment]
@airdrummingfool dummy solution for now... but works for me, let me know if this is also fine for you ?

**Comment by airdrummingfool** [comment]
@atoomic sorry for the delay. Your solution seems to prevent crashing the server, but it also makes my volume-ui requests take much longer (of course- there's a 750ms timeout before the lock is removed). In my tests, without the timeout and lock mechanism, my requests take ~22ms; with locking, ~772ms. 

That being said, I don't think that a delay is actually much of a concern - the only issue is if several volume changes get queued in a row, and this would only happen on accident. It seems like a good "dummy" solution to me.

I do have a couple questions/comments:

1. Wouldn't it be better to put the lock around the Telnet code in `do_request`? That way all requests to the server are protected, not just volume setting (though I've never been able to cause a crash outside of `set_volume`).
2. Do you have any theory as to why the timeout is needed in addition to the lock? I've done testing, and it is - but that doesn't make sense to me. The lock ensures that we're waiting until the previous request to `snapserver` completes before making another, so if that's not enough to prevent it from crashing, `snapserver` may be more sensitive than I originally thought.

Actually, I just realized that I'm running the perl server single-threaded  (using `./devel-server`). That means the requests have always been going to `snapserver` one at a time, and that, for me, the lock isn't actually doing anything.

I've done some more testing, with interesting results. I can drop the timeout to as low as 499ms without issue, but as soon as I change it to 498ms, I can consistently cause `snapserver` to crash by rapidly changing the volume (it's worth noting that these times hold with or without locking in place). 499ms is too close to exactly half a second to be a coincidence (especially given the ~1ms round-trip-time between my client and the server). Would you be willing to test and see if you can get the timeout down to 500ms (or even 499ms) as well?

**Comment by airdrummingfool** [comment]
The upstream issue has been fixed (see badaix/snapcast#200). I've removed all lock and sleep code from my local copy and everything is working great - no crashes, and volume changes happen very fast. You may wish to revert b0ec7cc3 and 33f670b9a.

**Comment by atoomic** [comment]
@airdrummingfool indeed I noticed the fix from upstream, glad you could test it and it works !
as this fix is going to 0.11 we still need the patch in the 0.10 branch but indeed this can be reverted in master and 0.11 branch.

Concerning the timeout I also tested 500 ms, but this value is highly dependent on your network.
In my case the UI and the snapcast server lives on two different servers.

1. yes you are right, it s a better choice to put the protection around the telnet calls !
2. indeed at first was thinking that a simple lock should fix the issue... then discovered that an extra sleep was required... i do not know yet but the upstream fix should give us more informations there

Thanks a lot for your feedback, will action your suggestions ( revert in 0.11 + move the protection to the telnet call for 0.10 ) in a short future.

**Comment by atoomic** [comment]
Only need it in 0.10.
Need to revert in master and provide a better fix for 0.10

**Comment by airdrummingfool** [comment]
Ah yes, my mistake. Of course this is still needed on 0.10 :)

Since my volume UI and snapserver live on the same server, my assumption was that my network is "ideal", and thus any network time is negligible. It seems to me that this would be the situation in which the sleep would need to be greatest (because there's no network lag to increase the time between requests). However, since the issue was found to be in the controlSession shutdown code, the timing may have also been affected by CPU speed and other factors outside of network timing. Either way, I doubt that a 250ms speedup is worth the additional testing necessary to make sure 500ms actually works in every situation.

**Comment by atoomic** [comment]
@airdrummingfool thanks for your feedbacks there.
I think we can safely close it for now, long life to v0.11 !
